service: my-esm-service

provider:
  name: aws
  runtime: nodejs22.x

functions:
  hello:
    handler: my-function.handler

# Optionally, you can exclude files from the packaged zip
package:
  patterns:
    - '!.gitignore'
    - '!.DS_Store'
    - '!README.md'
